import { Command } from 'commander';
import { writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';
import { ProviderRegistry } from '../../server/provider-registry.js';
import { LLM_PROVIDERS, SUBPROCESS_TOOLS } from '../../config/provider-catalog.js';

const API_KEY_VARS: Array<{ provider: string; vars: string[] }> = [
  { provider: 'deepseek', vars: ['DEEPSEEK_API_KEY'] },
  { provider: 'openai', vars: ['OPENAI_API_KEY'] },
  { provider: 'anthropic', vars: ['ANTHROPIC_API_KEY'] },
  { provider: 'gemini', vars: ['GEMINI_API_KEY'] },
  { provider: 'minimax', vars: ['MINIMAX_API_KEY', 'MINIMAX_CN_API_KEY'] },
  { provider: 'qwen', vars: ['QWEN_API_KEY'] },
  { provider: 'kimi', vars: ['MOONSHOT_API_KEY', 'KIMI_API_KEY'] },
];

function buildConfigYaml(port: string, detectedTools: string[], foundKeys: string[]): string {
  let yaml = `# Generated by \`am setup\` — auto-detected agents and API keys
# Edit this file to add more agents or change settings
# Full catalog: meetings.config.example.yml

server:
  port: ${port}
  host: "0.0.0.0"
  dataDir: "./data"

agents:
  # ── Browser agent (free — no API key needed) ──
  - id: chatgpt
    name: "ChatGPT"
    type: browser
    capabilities: [general, creative, brainstorming, coding]
    site: chatgpt
    timeoutMs: 120000
`;

  if (detectedTools.length > 0) {
    yaml += '\n  # ── Detected subprocess tools ──\n';
    for (const toolId of detectedTools) {
      const entry = SUBPROCESS_TOOLS[toolId];
      if (!entry) continue;
      const argsStr = JSON.stringify(entry.defaultArgs);
      yaml += `  - id: ${toolId}
    name: "${entry.name}"
    type: subprocess
    capabilities: [coding, building, debugging]
    command: ${entry.command}
    args: ${argsStr}
    promptMode: ${entry.defaultPromptMode}
    timeoutMs: ${entry.defaultTimeoutMs}
`;
    }
  }

  if (foundKeys.length > 0) {
    yaml += '\n  # ── API-based LLM agents ──\n';
    for (const providerId of foundKeys) {
      const entry = LLM_PROVIDERS[providerId];
      if (!entry) continue;
      const keyVar = API_KEY_VARS.find((p) => p.provider === providerId)?.vars[0] ?? '';
      yaml += `  - id: ${providerId}
    name: "${entry.name}"
    type: llm
    capabilities: [general, reasoning, coding]
    provider: ${providerId}
    model: ${entry.defaultModel}
    apiKey: "\${${keyVar}}"
`;
    }
  }

  if (detectedTools.length === 0 && foundKeys.length === 0) {
    yaml += `
  # ── No tools or API keys detected ──
  # Set DEEPSEEK_API_KEY in your environment or a .env file and re-run ` + '`am setup`' + `,
  # or uncomment the example below:
  # - id: deepseek
  #   name: "DeepSeek"
  #   type: llm
  #   capabilities: [architecture, planning, coding, analysis, reasoning]
  #   provider: deepseek
  #   model: deepseek-chat
  #   apiKey: "\${DEEPSEEK_API_KEY}"
`;
  }

  yaml += `
meetings:
  mode: debate
  turnTimeoutMs: 60000
  maxRebuttalRounds: 2
  maxDeliberationRounds: 3
`;

  if (foundKeys.includes('deepseek')) {
    yaml += '  defaultModerator: deepseek\n';
  } else if (detectedTools.length > 0) {
    yaml += `  defaultModerator: ${detectedTools[0]}\n`;
  } else {
    yaml += '  defaultModerator: chatgpt\n';
  }

  return yaml;
}

function openBrowser(url: string): void {
  const platform = process.platform;
  try {
    if (platform === 'darwin') {
      execSync(`open "${url}"`);
    } else if (platform === 'win32') {
      execSync(`start "" "${url}"`);
    } else {
      execSync(`xdg-open "${url}"`);
    }
    console.log(`Opened ${url} in your browser.`);
  } catch {
    console.log(`Open ${url} in your browser to get started.`);
  }
}

export function setupCommand(): Command {
  return new Command('setup')
    .description('Detect tools and API keys, write a starter config, and start the server')
    .option('--port <port>', 'Server port', '4200')
    .option('--no-open', 'Skip opening the browser')
    .option('--dry-run', 'Print the generated config instead of writing and starting')
    .action(async (options) => {
      const registry = new ProviderRegistry();
      const detected = registry.detectInstalled();

      console.log(`\nDetected ${detected.length} subprocess tool(s):`);
      if (detected.length > 0) {
        for (const id of detected) {
          const entry = SUBPROCESS_TOOLS[id];
          console.log(`  ✓ ${id} (${entry?.command ?? '?'})`);
        }
      } else {
        console.log('  (none found on PATH)');
      }

      const foundKeys: string[] = [];
      console.log(`\nAPI key scan:`);
      for (const { provider, vars } of API_KEY_VARS) {
        for (const v of vars) {
          if (process.env[v]) {
            foundKeys.push(provider);
            console.log(`  ✓ $${v} → ${LLM_PROVIDERS[provider]?.name ?? provider}`);
            break;
          }
        }
      }
      if (foundKeys.length === 0) {
        console.log('  (no API keys found in environment)');
      }

      const yaml = buildConfigYaml(options.port, detected, foundKeys);

      if (options.dryRun) {
        console.log('\n─── Generated config (dry run) ───\n');
        console.log(yaml);
        return;
      }

      const configPath = resolve('./meetings.config.yml');
      if (existsSync(configPath)) {
        console.warn(`\n⚠  ${configPath} already exists and will be overwritten.`);
      }

      writeFileSync(configPath, yaml, 'utf-8');
      console.log(`\nWrote config to ${configPath}`);

      console.log('Starting server...');
      const { createServer } = await import('../../server/index.js');
      const server = await createServer(configPath);
      await server.start();

      if (options.open) {
        openBrowser(`http://localhost:${options.port}`);
      }

      console.log('\n✓ Setup complete. The server is running. Press Ctrl+C to stop.');
    });
}